### PR TITLE
fix(sphere-stock-import): Add sphere error message in case of 409 err…

### LINKED ISSUE #78: Add sphere error message in case of 409 error in stock import
### Description
In stock import process when SDK returns 409 error importer retries a request 10 times and then rejects without a custom error message. 
```
debug "Failed to retry the task after #{@max409Retries} attempts for stock #{JSON.stringify(entry)}"
Promise.reject err
```
[my code is here](https://github.com/sphereio/sphere-stock-import/blob/79e68ef614dc19efeee236fd9e908e891f6e9039/src/coffee/stockimport.coffee#L386-L387)

### Expected Behavior
The errors (SDK and 409) should be shown to the user. 

### Current Behavior
Loosing track of the SDK error in case of error 409.

### Context
The library user will not know the reason the request was rejected  or did not qualify for retry at all.

### Possible Solution
Extending of original error with our custom/context specific message.

### PR DESCRIPTION
**Pull request by Babanila**
### Summary
Add sphere error message in case of 409 error in stock import

#### Description
In stock import process when SDK returns 409 error importer retries a request 10 times and then rejects without a custom error message. 

closes #78

### CODE REVIEW

File: src/coffee/stockimport.coffee [hunk 1]
```diff
@@ -384,6 +384,8 @@ class StockImport
                 Promise.reject err
           else
             debug "Failed to retry the task after #{@max409Retries} attempts for stock #{JSON.stringify(entry)}"
+            customMessage = "Failed to retry the task after #{@max409Retries} attempts for stock #{JSON.stringify(entry)}"
```
Comment (butenkor) [inline src/coffee/stockimport.coffee]: You could also reuse this variable in debug (line 386)
