### PR TITLE
fix(stock-import): Don't swallow an error from SDK in case of 409 err…

### LINKED ISSUE #73: Don't swallow an error from SDK in case of 409 error in stock import
### Description
In stock import process when SDK returns 409 error importer retries a request 10 times and then rejects with a custom error and swallows an actual error with Correlation ID.
https://github.com/sphereio/sphere-stock-import/blob/8cb1bed826013550d9d6013a6e00b9d328683a13/src/coffee/stockimport.coffee#L386

### Possible Solution
I think it'd be better if we extend the error from SDK with ours and rethrow it.

### PR DESCRIPTION
**Pull request by Babanila**
Summary
Don't swallow an error from SDK in case of 409 error in stock import

Description
In stock import process when SDK returns 409 error importer retries a request 10 times and then rejects with a custom error and swallows an actual error with Correlation ID.

@LEQADA is this okay with you ?
Closes #73

### CODE REVIEW

File: src/coffee/stockimport.coffee [hunk 1]
```diff
@@ -383,7 +383,8 @@ class StockImport
                 debug "Error on handling 409 stock update error. Details: #{JSON.stringify(err)}"
                 Promise.reject err
           else
-            Promise.reject new Error("Failed to retry the task after #{@max409Retries} attempts for stock #{JSON.stringify(entry)}")
+            debug "Failed to retry the task after #{@max409Retries} attempts for stock #{JSON.stringify(entry)}"
+            Promise.reject err
```
Comment (butenkor) [inline src/coffee/stockimport.coffee]: Hello @Babanila and welcome :) 

Thank you for addressing the issue. It is important for the library user to know if rejected request was retried or did not qualify for retry at all. This information is important for both log based statistics/alerts as in general for issue debugging/resolution.

As described in the ticket #73 

> I think it'd be better if we extend the error from SDK with ours and rethrow it.

please make sure that a message which currently is output as debug only is also included into rejected error. I am not sure what would be the best practice here as simple re-throw will unfortunately lose original stack trace but it might be good enough if we just extend original error with our custom/context specific message:

```
customMessage = "Failed to retry the task after #{@max409Retries} attempts for stock #{JSON.stringify(entry)}"
err.sphereStockImportErrorMessage = customMessage
Promise.reject err
```

Comment (butenkor) [reply src/coffee/stockimport.coffee]: Here we try to do the same but i guess we lose original stack trace and possibly other properties from the `e`: https://github.com/commercetools/nodejs/blob/master/packages/sdk-middleware-http/src/http.js#L177
